version: '3.9'

services:
  assistance-centers:
    extends:
      file: common.yml
      service: common
    container_name: assistance-centers
    image: turnly/assistance-centers:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/assistance-centers
      target: ${DOCKER_BUILD_STAGE}
      dockerfile: Dockerfile
      args:
        PORT: ${HTTP_PORT}
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/assistance-centers:/app
      - /app/node_modules
    depends_on:
      - gateway
      - mongo
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly
      - traefik.http.routers.assistance-centers-rpc.entrypoints=web,websecure
      - traefik.http.routers.assistance-centers-rpc.rule=PathPrefix(`/turnly.assistance_centers.v1`)
      - traefik.http.routers.assistance-centers-rpc.service=assistance-centers-rpc
      - traefik.http.services.assistance-centers-rpc.loadbalancer.server.scheme=h2c
    environment:
      # This service shared env variables that extend from common.yml
      APP_NAME: assistance-centers
      ENCRYPTION_SECRET:
      RABBITMQ_QUEUE: ${ASSISTANCE_CENTERS_RABBITMQ_QUEUE:-turnly.ms.assistance_centers.queue}
      MONGO_DB: ${ASSISTANCE_CENTERS_MONGO_DB:-assistance_centers_db}
