version: '3.9'

services:
  assistance-centers:
    extends:
      file: common.yml
      service: common
    container_name: assistance-centers
    image: turnly/assistance-centers:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/assistance-centers
      target: ${DOCKER_BUILD_STAGE}
      dockerfile: Dockerfile
      args:
        PORT: ${HTTP_PORT}
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/assistance-centers:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      turnly.network.internal:
        aliases:
          - assistance-centers.turnly.local
    environment:
      # This service shared env variables that extend from common.yml
      APP_NAME: assistance-centers
      ENCRYPTION_SECRET:
      RABBITMQ_QUEUE: ${ASSISTANCE_CENTERS_RABBITMQ_QUEUE:-turnly.ms.assistance_centers.queue}
      MONGO_DB: ${ASSISTANCE_CENTERS_MONGO_DB:-assistance_centers_db}
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    labels:
      # External access is used to test new gRPC endpoints with Bloom or Postman,
      # but in production, microservices communicate on the internal network, so gRPC APIs should not be exposed.
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal
      - traefik.http.routers.assistance-centers-internal.entrypoints=web
      - traefik.http.routers.assistance-centers-internal.service=assistance-centers-internal
      - traefik.http.services.assistance-centers-internal.loadbalancer.server.scheme=h2c
      - traefik.http.routers.assistance-centers-internal.rule=PathPrefix(`/turnly.assistance_centers.v1`)
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
