version: '3.9'

services:
  helpdesk-api:
    extends:
      file: common.yml
      service: common
    container_name: helpdesk-api
    image: turnly/helpdesk-api:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/helpdesk-api
      target: ${DOCKER_BUILD_STAGE}
      dockerfile: Dockerfile
      args:
        PORT: ${HTTP_PORT}
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/helpdesk-api:/app
    depends_on:
      - gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.helpdesk-api-http.entrypoints=web,websecure
      - traefik.http.routers.helpdesk-api-http.rule=PathPrefix(`/api/v1/helpdesk`)
      - traefik.http.routers.helpdesk-api-http.service=helpdesk-api-http
      - traefik.http.services.helpdesk-api-http.loadbalancer.server.port=${HTTP_PORT}
    environment:
      # This service shared env variables that extend from common.yml
      APP_NAME: helpdesk-api
