version: '3.9'

services:
  iam:
    extends:
      file: common.yml
      service: common
    container_name: heimdall-iam
    image: turnly/iam:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/iam
      dockerfile: Dockerfile
    ports:
      - ${IAM_PORT}:8080
    depends_on:
      postgres:
        condition: service_healthy
      gateway:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: ${IAM_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${IAM_ADMIN_PASSWORD}
      KC_DB_URL: ${IAM_DB_URL}
      KC_DB_USERNAME: ${IAM_DB_USERNAME}
      KC_DB_PASSWORD: ${IAM_DB_PASSWORD}
      KC_HOSTNAME: ${IAM_HOSTNAME}
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.addons-rpc.entrypoints=web,websecure
    #   - traefik.http.routers.addons-rpc.rule=PathPrefix(`/turnly.addons.v1`)
    #   - traefik.http.routers.addons-rpc.service=addons-rpc
    #   - traefik.http.services.addons-rpc.loadbalancer.server.scheme=h2c

