version: '3.9'

services:
  iam:
    extends:
      file: common.yml
      service: common
    container_name: iam
    image: turnly/iam:latest
    command: start-dev
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/iam
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - gateway
    environment:
      KEYCLOAK_ADMIN: ${IAM_ADMIN_USERNAME:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${IAM_ADMIN_PASSWORD:-admin}
      # KC_DB_URL: "jdbc:postgresql://postgres:5432/iam"
      # KC_DB_USERNAME: ${IAM_DB_USERNAME:-postgres}
      # KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${IAM_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.iam.entrypoints=web,websecure
      - traefik.http.routers.iam.rule=Host(`${IAM_HOSTNAME}`)
      - traefik.http.routers.iam.service=iam
      - traefik.http.services.iam.loadbalancer.server.port=8080
