version: '3.9'

services:
  queuing-system:
    extends:
      file: common.yml
      service: common
    container_name: queuing-system
    image: turnly/queuing-system:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/queuing-system
      target: ${DOCKER_BUILD_STAGE}
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/queuing-system:/app
    depends_on:
      elasticsearch: # Disable this if you are using an external ElasticSearch database
        condition: service_healthy
      mongo: # Disable this if you are using an external Mongo database
        condition: service_healthy
    networks:
      turnly.network.internal:
        aliases:
          - queuing-system.turnly.local
    environment:
      # This service shared env variables that extend from common.yml
      APP_NAME: queuing-system
      ENCRYPTION_SECRET:
      RABBITMQ_QUEUE: ${QUEUING_SYSTEM_RABBITMQ_QUEUE:-turnly.ms.queuing_system.queue}
      MONGO_DB: ${QUEUING_SYSTEM_MONGO_DB:-queuing_system_db}
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    labels:
      # External access is used to test new gRPC endpoints with Bloom or Postman,
      # but in production, microservices communicate on the internal network, so gRPC APIs should not be exposed.
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal
      - traefik.http.routers.queuing-system-internal.entrypoints=web
      - traefik.http.routers.queuing-system-internal.service=queuing-system-internal
      - traefik.http.services.queuing-system-internal.loadbalancer.server.scheme=h2c
      - traefik.http.routers.queuing-system-internal.rule=PathPrefix(`/turnly.queuing_system.v1`)
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
