version: "3.9"

services:
  teams:
    extends:
      file: common.yml
      service: common
    container_name: teams
    image: ghcr.io/turnly/teams:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/teams
      target: ${DOCKER_BUILD_STAGE}
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/teams:/app
    depends_on:
      elasticsearch: # Disable this if you are using an external ElasticSearch database
        condition: service_healthy
      mongo: # Disable this if you are using an external Mongo database
        condition: service_healthy
    networks:
      turnly.network.internal:
        aliases:
          - teams.turnly.local
    environment:
      # This service shared env variables that extend from common.yml
      APP_NAME: teams
      ENCRYPTION_SECRET:
      RABBITMQ_QUEUE: ${TEAMS_RABBITMQ_QUEUE:-turnly.ms.teams.queue}
      MONGO_DB: ${TEAMS_MONGO_DB:-teams_db}
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    labels:
      # External access is used to test new gRPC endpoints with Bloom or Postman,
      # but in production, microservices communicate on the internal network, so gRPC APIs should not be exposed.
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal
      - traefik.http.routers.teams-internal.entrypoints=web,websecure
      - traefik.http.routers.teams-internal.service=teams-internal
      - traefik.http.services.teams-internal.loadbalancer.server.scheme=h2c
      - traefik.http.routers.teams-internal.rule=PathPrefix(`/turnly.teams.v1`)
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
