addons:
  - apps/addons/**/*
assistance-centers:
  - apps/assistance-centers/**/*
custom-fields:
  - apps/custom-fields/**/*
queuing-system:
  - apps/queuing-system/**/*
documentation:
  - docs/**/*
environment:
  - .env.example
