version: '3.9'

services:
  minio:
    extends:
      file: common.yml
      service: common
    container_name: minio
    platform: linux/amd64
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_UI_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

volumes:
  minio_data:
