name: '🏷️ Setup Registry'
description: ''
outputs:
  VERSION:
    description: ''
    value: ${{ steps.version.outputs.VERSION }}

runs:
  using: composite
  steps:
    - name: 🏷️ Get the version
      shell: bash
      id: version
      run: echo "VERSION=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_OUTPUT

    - name: 🚜 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🔐 Login to GitHub Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
