version: '3.9'

services:
  rabbitmq:
    extends:
      file: common.yml
      service: common
    image: rabbitmq:3.10.5-management-alpine
    container_name: rabbitmq
    tty: true
    stdin_open: true
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    ports:
      - ${RABBITMQ_UI_PORT}:15672
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    expose:
      - 5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - rabbitmq.turnly.local
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'ping', '--silent']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
