version: '3.9'

# Delete elasticsearch.yml (this) file if you are using an external ElasticSearch database
services:
  elasticsearch:
    extends:
      file: common.yml
      service: common
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    expose:
      - 9200
    environment:
      discovery.type: "single-node"
      node.name: "turnly"
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      turnly.network.internal:
        aliases:
          - elasticsearch.turnly.local
    healthcheck:
      test: curl -s -f ${ELASTICSEARCH_URI}/_cat/health >/dev/null || exit 1
      interval: 20s
      timeout: 15s
      retries: 10

volumes:
  elasticsearch_data:
