version: '3.9'

services:
  elasticsearch:
    extends:
      file: common.yml
      service: common
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    expose:
      - ${ELASTICSEARCH_PORT}
    environment:
      discovery.type: "single-node"
      node.name: "turnly"
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
       - ${ELASTICSEARCH_PORT}:9200

volumes:
  elasticsearch_data:
