version: '3.9'

services:
  mongo_ui:
    extends:
      file: common.yml
      service: common
    container_name: mongo_ui
    image: mongo-express
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    ports:
      - ${MONGO_UI_PORT}:8081
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - mongo_ui.turnly.local
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
