version: '3.9'

services:
  mongo_ui:
    extends:
      file: common.yml
      service: common
    container_name: mongo_ui
    image: mongo-express
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - mongo_ui.turnly.local
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.mongo-public.entrypoints=mongo
      - traefik.http.routers.mongo-public.service=mongo-public
      - traefik.http.routers.mongo-public.rule=Host(`${APP_INFRA_DOMAIN}`)
      - traefik.http.services.mongo-public.loadbalancer.server.port=8081

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.mongo-public.middlewares=oauth-admin-middleware
