name: '🚀 Setup base images'
description: 'Pull base images & setting up the domains'
inputs:
  node-version:
    description: 'The node version'
    required: true

runs:
  using: composite
  steps:
    - name: 🚀 Setup Node
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Pull base dependencies
      shell: bash
      run: docker pull node:${{ inputs.node-version }}-alpine3.17
