version: '3.9'

services:
  gateway:
    extends:
      file: common.yml
      service: common
    image: turnly/gateway:latest
    container_name: gateway
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/gateway
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
      - ${TRAEFIK_UI_PORT}:8080
    # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
      - 80:80
      - 443:443
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - ${IAM_HOSTNAME}
          - ${APP_DOMAIN}

networks:
  turnly.network.internal:
    name: turnly.network.internal
    external: true
  turnly.network.public:
    name: turnly.network.public
    external: true
