version: '3.9'

services:
  gateway:
    extends:
      file: common.yml
      service: common
    image: turnly/gateway:latest
    command:
      - --accesslog=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=turnly.network.internal
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.rabbitmq.address=:${RABBITMQ_UI_PORT}
      - --entrypoints.kibana.address=:${ELASTICSEARCH_UI_PORT}
      - --entrypoints.postgres.address=:${POSTGRES_ADMINER_PORT}
      - --entrypoints.mongo.address=:${MONGO_UI_PORT}
      - --entrypoints.redis.address=:${REDIS_UI_PORT}
      - --entrypoints.storage.address=:${MINIO_UI_PORT}
      - --entrypoints.tracing.address=:${TRACING_UI_PORT}
    container_name: gateway
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/gateway
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
      - ${TRAEFIK_UI_PORT}:8080
      # ----------------------> WARNING: FOR DEVELOPMENT ONLY <----------------------
      - ${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}
      - ${ELASTICSEARCH_UI_PORT}:${ELASTICSEARCH_UI_PORT}
      - ${POSTGRES_ADMINER_PORT}:${POSTGRES_ADMINER_PORT}
      - ${MONGO_UI_PORT}:${MONGO_UI_PORT}
      - ${REDIS_UI_PORT}:${REDIS_UI_PORT}
      - ${MINIO_UI_PORT}:${MINIO_UI_PORT}
      - ${TRACING_UI_PORT}:${TRACING_UI_PORT}
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - ${IAM_HOSTNAME}
          - ${APP_DOMAIN}

  error-pages:
    image: tarampampam/error-pages:2.19.0
    container_name: gateway-error-pages
    environment:
      TEMPLATE_NAME: app-down
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      # use as "fallback" for any NON-registered services (with priority below normal)
      - traefik.http.routers.error-pages-router.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.error-pages-router.priority=10

      - traefik.http.routers.error-pages-router.entrypoints=web,websecure
      - traefik.http.routers.error-pages-router.middlewares=error-pages-middleware

      - traefik.http.middlewares.error-pages-middleware.errors.status=400-599
      - traefik.http.middlewares.error-pages-middleware.errors.service=error-pages-service
      - traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html
      - traefik.http.services.error-pages-service.loadbalancer.server.port=8080
    depends_on:
      - gateway
    networks:
      - turnly.network.public
      - turnly.network.internal

networks:
  turnly.network.internal:
    name: turnly.network.internal
    external: true
  turnly.network.public:
    name: turnly.network.public
    external: true
