version: '3.9'

services:
  gateway:
    extends:
      file: common.yml
      service: common
    image: turnly/gateway:latest
    container_name: gateway
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/gateway
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${TRAEFIK_UI_PORT}:8080
      - 80:80
      - 443:443
    networks:
      turnly:

  gateway-forward-auth:
    image: mesosphere/traefik-forward-auth:3.1.0
    container_name: gateway-forward-auth
    depends_on:
      - iam
    environment:
      ENCRYPTION_KEY: ${IAM_ENCRYPTION_KEY}
      SECRET: ${IAM_SIGNING_KEY}
      PROVIDER_URI: ${IAM_OIDC_PROVIDER_URI}
      CLIENT_ID: ${IAM_OIDC_CLIENT_ID}
      CLIENT_SECRET: ${IAM_OIDC_CLIENT_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.gateway-forward-auth.entrypoints=web,websecure
      - traefik.http.services.gateway-forward-auth.loadbalancer.server.port=4181
      - traefik.http.routers.gateway-forward-auth.rule=Path(`/_oauth`)
      - traefik.http.routers.gateway-forward-auth.middlewares=traefik-forward-auth
      - traefik.http.middlewares.traefik-forward-auth.gateway-forward-auth.address=http://gateway-forward-auth:4181
      - traefik.http.middlewares.traefik-forward-auth.gateway-forward-auth.authResponseHeaders=X-Forwarded-User
      - traefik.http.middlewares.traefik-forward-auth.gateway-forward-auth.trustForwardHeader=true
    networks:
      turnly:

networks:
  turnly:
