version: '3.9'

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: 3
      max-size: 10m

services:
  common:
    <<: *logging
    restart: unless-stopped
    networks:
      turnly.network.internal:
    environment:
      - NODE_ENV
      - APP_EDITION
      - APP_DOMAIN
      - RPC_CONSUMER_ADDRESS
      - APP_PORT
      - LOGGING_LEVEL
      - SENTRY_DSN
      - FLUENT_HOST
      - FLUENT_PORT
      - TRACING_ENDPOINT
      - MONGO_URI
      - REDIS_HOST
      - REDIS_PASSWORD
      - ELASTICSEARCH_URI
      - RABBITMQ_URI
      - RABBITMQ_EXCHANGE
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER
      - DB_DEBUG
