name: 🔋 CI - Test Suites

on:
  pull_request:
    paths:
      - apps/**
    branches:
      - develop
      - main
  workflow_dispatch:

  push:
    paths:
      - apps/**
      - .github/workflows/continuous-integration-tests.yml
    branches:
      - develop
      - main

jobs:
  unit_and_integration:
    name: 🧩 Unit & Integration
    uses: ./.github/workflows/unit-and-integration-tests.yml
    with:
      mongo-username: root
      mongo-password: turnly
      mongo-db: turnly_testing_db

  e2e_and_benchmark:
    name: 🧩 E2E & Benchmark
    uses: ./.github/workflows/e2e-and-benchmark-tests.yml
