name: 🏷️ CI - Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  registry:
    name: 📦 Build, Package, and ship to GitHub Registry
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: 🎬 Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
