name: 🧩 E2E & Benchmark

on: [workflow_call]

jobs:
  tests:
    name: 🎲 Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14]
        mongodb-version: [5.0.9]

    steps:
      - name: 🏷️ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 🔍 Map the changes to the appropriate applications
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/filters.yml

      - name: 🕒 Please wait, the next step will take a few minutes...
        run: echo "..."

      - name: 🐳 Setup the environment
        uses: ./.github/actions/setup-docker-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🚀 Start all applications
        run: yarn start --verbose

      - name: "🧪 [Branch Management]: run e2e tests"
        if: steps.filter.outputs.branch-management == 'true'
        run: yarn test:e2e --scope=@turnly/branch-management

      - name: "🧪 [Branch Management]: run benchmark tests"
        if: steps.filter.outputs.branch-management == 'true'
        run: yarn test:benchmark --scope=@turnly/branch-management

      - name: "🧪 [Business Data Fields]: run e2e tests"
        if: steps.filter.outputs.business-data-fields == 'true'
        run: yarn test:e2e --scope=@turnly/business-data-fields

      - name: "🧪 [Business Data Fields]: run benchmark tests"
        if: steps.filter.outputs.business-data-fields == 'true'
        run: yarn test:benchmark --scope=@turnly/business-data-fields

      - name: "🧪 [Queuing System]: run e2e tests"
        if: steps.filter.outputs.queuing-system == 'true'
        run: yarn test:e2e --scope=@turnly/queuing-system

      - name: "🧪 [Queuing System]: run benchmark tests"
        if: steps.filter.outputs.queuing-system == 'true'
        run: yarn test:benchmark --scope=@turnly/queuing-system

      - name: 🔥 Teardown
        if: always()
        run: yarn stop --verbose
