name: 📦 CI - Helpdesk API Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  registry:
    name: 📦 Build, Package, and ship to GitHub Registry
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: 🎬 Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 🚀 Setup Registry
        uses: ./.github/actions/setup-registry
        id: registry
        with:
          password: ${{ secrets.CR_PAT }}

      - name: 🐳 Push Helpdesk API to GitHub Registry
        uses: docker/build-push-action@v3
        with:
          context: "./apps/helpdesk-api"
          target: production
          push: true
          tags: |
            ghcr.io/turnly/helpdesk-api:v${{ steps.registry.outputs.VERSION }}
            ghcr.io/turnly/helpdesk-api:latest
