name: 🔋 CI - Test Suites

on:
  pull_request:
    paths:
      - apps/**
    branches:
      - develop
      - main
  workflow_dispatch:

  push:
    paths:
      - apps/**
      - .github/workflows/tests.global.ci.yml
    branches:
      - develop
      - main

jobs:
  unit_and_integration:
    name: 🧩 Unit & Integration
    uses: ./.github/workflows/tests.global-unit-integration.ci.yml
    with:
      mongo-username: root
      mongo-password: turnly
      mongo-db: testing-db

  e2e_and_benchmark:
    name: 🧩 E2E & Benchmark
    uses: ./.github/workflows/tests.global-e2e-and-benchmark.ci.yml
