version: '3.9'

services:
  fluentd:
    extends:
      file: common.yml
      service: common
    container_name: fluentd
    platform: linux/amd64
    image: turnly/fluentd:latest
    build: ./infrastructure/observability/fluentd
    volumes:
      - ./infrastructure/observability/fluentd/conf:/fluentd/etc:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    expose:
      - 24224
      - 24224/udp
    networks:
      turnly.network.internal:
        aliases:
          - logging.turnly.local
